# Generated by Django 2.1.7 on 2022-07-16 12:31

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('state', models.CharField(choices=[('initial', 'initial'), ('preparing', 'preparing'), ('declined', 'declined'), ('in_progress', 'in_progress'), ('finished', 'finished')], default='initial', max_length=15)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
                ('finished', models.DateTimeField(blank=True, default=None, null=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('players', models.ManyToManyField(related_name='games', to='players.Player')),
                ('winner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_a', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('player_b', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('game', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='games.Game')),
                ('question', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
                ('winner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='players.Player')),
            ],
        ),
    ]
