# Generated by Django 2.1.7 on 2019-05-05 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_auto_20190505_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='question',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Question'),
        ),
    ]
