# Generated by Django 2.1.7 on 2019-05-12 16:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20190505_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='round',
            name='player_a',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='player_b',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=None, null=True),
        ),
    ]
